"""empty message

Revision ID: 602aa76b61a2
Revises: 67286488ad2d
Create Date: 2024-03-06 13:03:51.163821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602aa76b61a2'
down_revision = '67286488ad2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
